### PR TITLE
refactored to support fomantic ui packages.

### PR DESCRIPTION
**Pull request by eser**
the subject is self-explanatory :)

### CODE REVIEW

**Comment by layershifter** [comment]
AFAIK it's not a problem with FUI as they fixed it. Is it really needed?

**Comment by eser** [comment]
I read the similar comments on GitHub Issues, but I had the same problem with Fomantic UI while working on [darty-react-app](https://github.com/eserozvataf/darty-react-app). maybe it's just me.

**Comment by layershifter** [comment]
@eserozvataf I was sure that it's fixed there and _it is_, but haven't been released yet (https://github.com/fomantic/Fomantic-UI/pull/2028).

Thanks 👍

**Review by layershifter — APPROVED** [review]

**Comment by layershifter** [comment]
@eserozvataf `@semantic-ui-react/css-patch@1.1.0` is there 🚢

**Pull request merged**
